/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.13
 * Generated at: 2026-08-28 17:58:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;

public final class carrier_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Carrier Logistics Terminal</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/styles/shadcn-base.css\">\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/theme-switch.js\"></script>\n");
      out.write("    <style>\n");
      out.write("        .dashboard-container { max-width: 1200px; margin: 0 auto; padding: 2rem; }\n");
      out.write("        .grid { display: grid; grid-template-columns: 2fr 1fr; gap: 2rem; }\n");
      out.write("        .list-group { list-style: none; padding: 0; margin: 0; }\n");
      out.write("        .list-item { padding: 0.75rem; border-bottom: 1px solid var(--border); }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div style=\"position: absolute; top: 1rem; right: 1rem; display: flex; gap: 1rem;\">\n");
      out.write("        <span class=\"text-sm items-center flex\">User: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("        <button id=\"theme-toggle\" class=\"btn btn-secondary text-sm\">Dark Mode</button>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" class=\"btn btn-secondary text-sm\">Logout</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"dashboard-container\">\n");
      out.write("        <h1 class=\"text-2xl font-semibold mb-6\">Carrier Logistics Terminal</h1>\n");
      out.write("\n");
      out.write("        ");
 if (session.getAttribute("successMessage") != null) { 
      out.write("\n");
      out.write("            <div class=\"mb-6 p-4 text-sm\" style=\"background-color: #22c55e; color: white; border-radius: var(--radius);\">\n");
      out.write("                ");
      out.print( session.getAttribute("successMessage") );
      out.write("\n");
      out.write("                ");
 session.removeAttribute("successMessage"); 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        \n");
      out.write("        ");
 if (session.getAttribute("errorMessage") != null) { 
      out.write("\n");
      out.write("            <div class=\"mb-6 p-4 text-sm\" style=\"background-color: var(--destructive); color: var(--destructive-foreground); border-radius: var(--radius);\">\n");
      out.write("                ");
      out.print( session.getAttribute("errorMessage") );
      out.write("\n");
      out.write("                ");
 session.removeAttribute("errorMessage"); 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"grid\">\n");
      out.write("            <div class=\"card p-6\">\n");
      out.write("                <h2 class=\"text-xl font-semibold mb-4\">Unified Shipping Manifest</h2>\n");
      out.write("                <ul class=\"list-group\">\n");
      out.write("                ");
 
                    List<String> manifest = (List<String>) request.getAttribute("manifest");
                    if (manifest != null && !manifest.isEmpty()) {
                        for (String line : manifest) {
                
      out.write("\n");
      out.write("                    <li class=\"list-item\">");
      out.print( line );
      out.write("</li>\n");
      out.write("                ");
 
                        }
                    } else {
                
      out.write("\n");
      out.write("                    <li class=\"list-item\">No packages currently waiting for transit.</li>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"card p-6\">\n");
      out.write("                <h2 class=\"text-xl font-semibold mb-4\">Update Transit Status</h2>\n");
      out.write("                \n");
      out.write("                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard/carrier\" method=\"POST\" class=\"flex flex-col gap-4\">\n");
      out.write("                    <div>\n");
      out.write("                        <label class=\"label\">Tracking Number</label>\n");
      out.write("                        <input type=\"text\" name=\"trackingNumber\" class=\"input\" required>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div>\n");
      out.write("                        <label class=\"label\">Action</label>\n");
      out.write("                        <select name=\"action\" class=\"input\">\n");
      out.write("                            <option value=\"pickup\">Mark IN_TRANSIT (Pickup)</option>\n");
      out.write("                            <option value=\"deliver\">Mark DELIVERED (Drop-off)</option>\n");
      out.write("                            <option value=\"breakdown\">Trigger BREAKDOWN (Simulate Outage)</option>\n");
      out.write("                        </select>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <button type=\"submit\" class=\"btn\">Update Status</button>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
