/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.13
 * Generated at: 2026-08-28 17:57:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.globaltrade.core.entity.Shipment;
import java.util.List;

public final class customs_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.globaltrade.core.entity.Shipment");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Government Customs Terminal</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/styles/shadcn-base.css\">\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/theme-switch.js\"></script>\n");
      out.write("    <style>\n");
      out.write("        .dashboard-container { max-width: 1000px; margin: 0 auto; padding: 2rem; }\n");
      out.write("        table { width: 100%; border-collapse: collapse; margin-top: 1rem; }\n");
      out.write("        th, td { text-align: left; padding: 0.75rem; border-bottom: 1px solid var(--border); }\n");
      out.write("        th { font-weight: 600; color: var(--muted-foreground); }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div style=\"position: absolute; top: 1rem; right: 1rem; display: flex; gap: 1rem;\">\n");
      out.write("        <span class=\"text-sm items-center flex\">User: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.username}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("        <button id=\"theme-toggle\" class=\"btn btn-secondary text-sm\">Dark Mode</button>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" class=\"btn btn-secondary text-sm\">Logout</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"dashboard-container\">\n");
      out.write("        <h1 class=\"text-2xl font-semibold mb-6\">Government Customs Clearance Terminal</h1>\n");
      out.write("\n");
      out.write("        ");
 if (session.getAttribute("successMessage") != null) { 
      out.write("\n");
      out.write("            <div class=\"mb-6 p-4 text-sm\" style=\"background-color: #22c55e; color: white; border-radius: var(--radius);\">\n");
      out.write("                ");
      out.print( session.getAttribute("successMessage") );
      out.write("\n");
      out.write("                ");
 session.removeAttribute("successMessage"); 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        \n");
      out.write("        ");
 if (session.getAttribute("errorMessage") != null) { 
      out.write("\n");
      out.write("            <div class=\"mb-6 p-4 text-sm\" style=\"background-color: var(--destructive); color: var(--destructive-foreground); border-radius: var(--radius);\">\n");
      out.write("                ");
      out.print( session.getAttribute("errorMessage") );
      out.write("\n");
      out.write("                ");
 session.removeAttribute("errorMessage"); 
      out.write("\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"card p-6\">\n");
      out.write("            <h2 class=\"text-xl font-semibold mb-4\">Pending Shipments Awaiting Clearance</h2>\n");
      out.write("            <div style=\"overflow-x: auto;\">\n");
      out.write("                <table>\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>Shipment ID</th>\n");
      out.write("                            <th>Tracking Number</th>\n");
      out.write("                            <th>Vendor</th>\n");
      out.write("                            <th>Action</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                    ");
 
                        List<Shipment> pending = (List<Shipment>) request.getAttribute("pending");
                        if (pending != null && !pending.isEmpty()) {
                            for (Shipment s : pending) {
                                String vendorName = s.getVendor() != null ? s.getVendor().getName() : "Unknown";
                    
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td>#");
      out.print( s.getId() );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( s.getTrackingNumber() );
      out.write("</td>\n");
      out.write("                            <td>");
      out.print( vendorName );
      out.write("</td>\n");
      out.write("                            <td>\n");
      out.write("                                <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/dashboard/customs\" method=\"POST\" class=\"flex gap-2\" style=\"margin:0;\">\n");
      out.write("                                    <input type=\"hidden\" name=\"shipmentId\" value=\"");
      out.print( s.getId() );
      out.write("\">\n");
      out.write("                                    <button type=\"submit\" name=\"action\" value=\"approve\" class=\"btn text-sm\" style=\"height:2rem; background-color: #22c55e; color: white;\">Approve</button>\n");
      out.write("                                    <button type=\"submit\" name=\"action\" value=\"reject\" class=\"btn text-sm\" style=\"height:2rem; background-color: #ef4444; color: white;\">Reject</button>\n");
      out.write("                                </form>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                    ");
 
                            }
                        } else {
                    
      out.write("\n");
      out.write("                        <tr><td colspan=\"4\">No shipments currently waiting for clearance.</td></tr>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
