/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.13
 * Generated at: 2026-08-29 07:06:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>GlobalTrade SCM - Client Portal</title>\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap\" rel=\"stylesheet\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/styles/shadcn-base.css\">\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/scripts/theme-switch.js\"></script>\n");
      out.write("    <style>\n");
      out.write("        .login-container {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: center;\n");
      out.write("            min-height: 100vh;\n");
      out.write("            padding: 1rem;\n");
      out.write("        }\n");
      out.write("        .theme-toggle-wrapper {\n");
      out.write("            position: absolute;\n");
      out.write("            top: 1rem;\n");
      out.write("            right: 1rem;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"theme-toggle-wrapper\">\n");
      out.write("        <button id=\"theme-toggle\" class=\"btn btn-secondary text-sm\">Dark Mode</button>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"login-container\">\n");
      out.write("        <div class=\"card p-6 w-full max-w-md\">\n");
      out.write("            <div class=\"text-center mb-6\">\n");
      out.write("                <h1 class=\"text-2xl font-semibold mb-2\">Terminal Portal Login</h1>\n");
      out.write("                <p class=\"text-sm text-muted-foreground\">Select your subsystem and authenticate to connect to the GlobalTrade Logistics engine.</p>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            ");
 if (request.getAttribute("errorMessage") != null) { 
      out.write("\n");
      out.write("                <div class=\"mb-4 p-4 text-sm\" style=\"background-color: var(--destructive); color: var(--destructive-foreground); border-radius: var(--radius);\">\n");
      out.write("                    ");
      out.print( request.getAttribute("errorMessage") );
      out.write("\n");
      out.write("                </div>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("            <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/login\" method=\"POST\" class=\"flex flex-col gap-4\">\n");
      out.write("                <div>\n");
      out.write("                    <label for=\"systemSelect\" class=\"label\">System</label>\n");
      out.write("                    <select id=\"systemSelect\" name=\"system\" class=\"input\" required>\n");
      out.write("                        <option value=\"1\">Hospital Ordering Portal</option>\n");
      out.write("                        <option value=\"2\">Warehouse Management Terminal</option>\n");
      out.write("                        <option value=\"3\">Carrier Logistics Terminal</option>\n");
      out.write("                        <option value=\"4\">Vendor/Supplier Portal</option>\n");
      out.write("                        <option value=\"5\">Government Customs Terminal</option>\n");
      out.write("                    </select>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div>\n");
      out.write("                    <label for=\"username\" class=\"label\">Username</label>\n");
      out.write("                    <input type=\"text\" id=\"username\" name=\"username\" class=\"input\" required>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <div>\n");
      out.write("                    <label for=\"password\" class=\"label\">Password</label>\n");
      out.write("                    <input type=\"password\" id=\"password\" value=\"password123\" name=\"password\" class=\"input\" required>\n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("                <button type=\"submit\" class=\"btn w-full mt-2\">Connect to Engine</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        const credentials = {\n");
      out.write("            \"1\": { u: \"hospitaladmin\", p: \"password123\" },\n");
      out.write("            \"2\": { u: \"warehousestaff\", p: \"password123\" },\n");
      out.write("            \"3\": { u: \"carrierdriver\", p: \"password123\" },\n");
      out.write("            \"4\": { u: \"vendor1\", p: \"password123\" },\n");
      out.write("            \"5\": { u: \"customsagent\", p: \"password123\" }\n");
      out.write("        };\n");
      out.write("\n");
      out.write("        const systemSelect = document.getElementById('systemSelect');\n");
      out.write("        const usernameInput = document.getElementById('username');\n");
      out.write("        const passwordInput = document.getElementById('password');\n");
      out.write("\n");
      out.write("        function updateCredentials() {\n");
      out.write("            const val = systemSelect.value;\n");
      out.write("            if (credentials[val]) {\n");
      out.write("                usernameInput.value = credentials[val].u;\n");
      out.write("                passwordInput.value = credentials[val].p;\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        systemSelect.addEventListener('change', updateCredentials);\n");
      out.write("        // Initialize on page load\n");
      out.write("        window.addEventListener('DOMContentLoaded', updateCredentials);\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
